### PR TITLE
Minor fix for Rails 3

### PR DESCRIPTION
**Pull request by CodeMonkeySteve**
Cheers!

### CODE REVIEW

**Comment by myronmarston** [comment]
Thanks, Steve.  I haven't had the time to look into this yet, but that change makes sense.  Could you add some test coverage for it?

**Comment by CodeMonkeySteve** [comment]
Will do.

**Comment by CodeMonkeySteve** [comment]
There you go.  Actually, I didn't need to add any tests, just needed to make the HTML-escaping behave the same in test as in development, then the existing HTML tests fail without the fix.

**Comment by CodeMonkeySteve** [comment]
One more fix, needed to run the tests under rspec v2.0.  Made this a separate commit, as I'm not sure if you (and everyone else) are ready to upgrade.

**Comment by myronmarston** [comment]
Thanks, Steve.  I just released 0.3.1 with your fixes.

**Pull request merged**
